plugins {
    id 'com.android.application'
    id 'checkstyle'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.sprintproject'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.sprintproject"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8

    }

    buildFeatures {
        dataBinding true
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'

    // firebase
    implementation 'com.google.firebase:firebase-auth:23.0.0'
    implementation 'com.google.firebase:firebase-firestore:25.0.0'

    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'com.google.android.material:material:1.9.0'
    // AndroidX Lifecycle (MVVM)
    implementation 'androidx.lifecycle:lifecycle-runtime:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.6.1'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    testImplementation "org.robolectric:robolectric:4.11.1"
    testImplementation "org.mockito:mockito-core:5.11.0"
    testImplementation "androidx.test:core:1.5.0"
}

// CheckStyle configuration
checkstyle {
    toolVersion = '10.12.3'
    configFile = file("${project.rootDir}/config/checkstyle/checkstyle.xml")
    ignoreFailures = false
    showViolations = true
}

task checkstyle(type: Checkstyle) {
    description = 'Check code style'
    group = 'verification'
    source 'src'
    include '**/*.java'
    exclude '**/gen/**'
    exclude '**/R.java'
    exclude '**/BuildConfig.java'

    classpath = files()

    reports {
        xml.required = true
        html.required = true
        html.outputLocation = file("$project.buildDir/reports/checkstyle/checkstyle.html")
    }
}